name: Create Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的 tag 时触发，如 v1.0, v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build plugin
        run: ./gradlew buildPlugin
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/distributions/defargs-intellij-plugin-1.0-SNAPSHOT.zip
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

